CinemaHub/Areas/CinemaManager/Controllers/PromotionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Metadata;
using Microsoft.AspNetCore.Mvc;
using CinemaHub.DataAccess.Repositories;
using CinemaHub.Models;
using CinemaHub.Services;
using static Org.BouncyCastle.Crypto.Engines.SM2Engine;

namespace CinemaHub.Areas.CinemaManager.Controllers
{
    [Area("CinemaManager")]
    [Authorize(Roles = "cinemaManager,admin")]
    public class PromotionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly UploadImageService _uploadImageService;
		public PromotionController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment, UploadImageService uploadImageService)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
			_uploadImageService = uploadImageService;

		}
		[HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Promotion promotion, IFormFile? fileImage)
		{
            if (ModelState.IsValid)
            {
                if (fileImage != null && fileImage.Length > 0)
                {
                    promotion.ImageUrl = _uploadImageService.UploadImage(fileImage, @"images\promotion");
                }
                else
                {
                    promotion.ImageUrl = null;
                }

                _unitOfWork.Promotion.Add(promotion);
                _unitOfWork.Save();
                TempData["msg"] = "Promotion created succesfully";

            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid promotion_id)
        {
            var promotion = await _unitOfWork.Promotion.GetFirstOrDefaultAsync(u => u.PromotionID == promotion_id);
            if (promotion == null)
            {
                return NotFound();
            }
            else
            {
                return View(promotion);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
		public async Task<IActionResult> Update(Promotion promotion, IFormFile? fileImage)
        {
			var _promotion = await _unitOfWork.Promotion.GetFirstOrDefaultAsync(u => u.PromotionID == promotion.PromotionID);
            _promotion.Topic = promotion.Topic;
            _promotion.Content = promotion.Content;
            _promotion.StartDate = promotion.StartDate;
            _promotion.EndDate = promotion.EndDate;
			if (ModelState.IsValid)
			{
				if (fileImage is not null)
				{
                    var old = _promotion.ImageUrl;
					_promotion.ImageUrl = _uploadImageService.UploadImage(fileImage, @"images\promotion", old);
				}
					
				_unitOfWork.Promotion.Update(_promotion);
				_unitOfWork.Save();
                TempData["msg"] = "Promotion updated succesfully";

            }
            return RedirectToAction("Index");
        }

        #region API Calls
        [HttpGet]
        public async Task<IActionResult> GetAllPromotions()
        {
            var promotions = await _unitOfWork.Promotion.GetAllAsync();
            return Json(new { data = promotions });
        }
        
        [HttpDelete]
        public async Task<IActionResult> Delete(Guid promotion_id)
        {
            var promotion = await _unitOfWork.Promotion.GetFirstOrDefaultAsync(u => u.PromotionID == promotion_id);
            if (promotion == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.Promotion.Delete(promotion);
            _unitOfWork.Save();
            return Json(new { success = true, message = "Delete promotion successfully! " });
        }
        #endregion
    }
}

CinemaHub/Areas/CinemaManager/Views/Promotion/Create.cshtml
@model Promotion
<div class="container my-5" style="min-height:840px">
    <h3 class="text-dark">New Promotion</h3>
    <hr />
    <form method="post" asp-action="Create" asp-controller="Promotion" enctype="multipart/form-data">
        <div class="row">
            <div class="my-3">
                <label asp-for="@Model.Topic" class="form-label">Topic name</label>
                <input type="text" asp-for="@Model.Topic" class="form-control">
                <span asp-validation-for="@Model.Topic" class="text-danger"></span>

            </div>
            <div class="col-12 mt-5">
                <label asp-for="@Model.Content">Content</label>
                <textarea asp-for="@Model.Content" rows="3" class="form-control"> </textarea>
                <span asp-validation-for="@Model.Content" class="text-danger"></span>
            </div>
            <div class="col-12 mt-5">
                <label asp-for="@Model.StartDate">Start Date</label>
                <input asp-for="@Model.StartDate" rows="3" class="form-control"> </input>
                <span asp-validation-for="@Model.StartDate" class="text-danger"></span>
            </div>
            <div class="col-12 mt-5">
                <label asp-for="@Model.EndDate">End Date</label>
                <input asp-for="@Model.EndDate" rows="3" class="form-control"> </input>
                <span asp-validation-for="@Model.EndDate" class="text-danger"></span>
            </div>
            <div class="col-12 mt-5">
                <label asp-for="@Model.ImageUrl">ImageUrl</label>
                <input type="file" name="fileImage" asp-for="@Model.ImageUrl" rows="3" class="form-control" />
                <span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
            </div>
        </div>
        <button type="submit" class="btn btn-dark my-3">Create</button>
        <a asp-controller="Promotion" asp-action="Index" class="btn btn-secondary my-3" style="width:200px">
            Back to Promotion list
        </a>
    </form>
</div>


@*Validate on client side*@
@section Scripts {

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        tinymce.init({
            selector: 'textarea',
            plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
            toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
        });

        $(document).ready(function () {
            var currentDate = new Date();

            $("form").submit(function () {
                var selectedStartDate = new Date($("#StartDate").val());
                var selectedEndDate = new Date($("#EndDate").val());

                if (selectedEndDate < selectedStartDate) {
                   // alert("End date must be greater than the start date.");
                    toastr.options = {
                        "closeButton": true
                    }
                    toastr.error('End date must be greater than the start date.');
                    return false;
                }
            });
        });



    </script>
    <partial name="_ValidationScriptsPartial" />
}

CinemaHub/Areas/CinemaManager/Views/Promotion/Index.cshtml
@model IEnumerable<Promotion>

<div class="container my-5" style="min-height:840px">

	<h3 class="text-dark">Manage Promotion</h3>
	<hr />
	<div class="d-flex w-100 my-5 justify-content-end">
		<a class="btn btn-dark mx-2" asp-controller="Promotion" asp-action="Create">
			<i class="bi bi-plus-circle"></i>
			Add new Promotion
		</a>
	</div>

	<table id="promotionTable" class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Topic</th>
				<th>Content</th>
				<th>StartDate</th>
				<th>EndDate</th>
				<th>Image</th>
				<th></th>
			</tr>
		</thead>
	</table>
	<div class="d-flex w-100 my-5 justify-content-start error-actions">
		<a class="btn btn-warning mx-2" asp-area="Customer" asp-controller="Home" asp-action="Index">
			<i class="bi bi-house"></i> Back to Home
		</a>
	</div>
</div>

@section Scripts {
	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
	<script>
		var dataTable;
		$(document).ready(function () {
			loadDataTable();
		})

		function loadDataTable() {
			dataTable = $('#promotionTable').DataTable({
				"ajax": {
					"url": "/CinemaManager/Promotion/GetAllPromotions"
				},
				"columns": [
					{ "data": "topic", "width": "10%" },
					{
						"data": "content",
						"width": "20%",
						"render": function (data) {
							return '<div class="content-cell">' + data + '</div>';
						}
					},
					{
						"data": "startDate",
						"width": "10%",
						"render": function (data) {
							return moment(data).format('MM-DD-YYYY HH:mm:ss');
						}
					},
					{
						"data": "endDate",
						"width": "10%",
						"render": function (data) {
							return moment(data).format('MM-DD-YYYY HH:mm:ss');
						}
					},
					{
						"data": "imageUrl",
						"render": function (data) {
							return '<td class="image-column" style="height:150px"><img src="' + data + '" alt="Alternate Text" class=" img-fluid image-element" /></td>';
						},
						"width": "15%"
					},
					{
						"data": "promotionID",
						"render": function (data) {
							return '<a href="/CinemaManager/Promotion/Update?promotion_id=' + data + '" class="btn btn-dark mx-2"><i class="bi bi-pencil-square"></i> Edit</a><a onClick=Delete(\'/CinemaManager/Promotion/Delete?promotion_id=' + data + '\') class="btn btn-danger mx-2 mt-2"><i class="bi bi-trash-fill"></i> Delete</a>';
						},
						"width": "15%"
					}
				]
			});
		}

		// SweetAlert library
		function Delete(url) {
			Swal.fire({
				title: 'Are you sure?',
				text: "You won't be able to revert this!",
				icon: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#3085d6',
				cancelButtonColor: '#d33',
				confirmButtonText: 'Yes, delete it!'
			}).then((result) => {
				if (result.isConfirmed) {
					$.ajax({
						url: url,
						type: 'DELETE',
						success: function (data) {
							if (data.success) {
								dataTable.ajax.reload();
								Swal.fire(
									'Deleted!',
									'This promotion has been deleted.',
									'success'
								)
							} else {
								//toastr.error(data.message);
							}
						}
					})
				}
			})
		}
	</script>

}

CinemaHub/Areas/CinemaManager/Views/Promotion/Update.cshtml
@model Promotion
<div class="container my-5" style="min-height:840px">
	<h3 class="text-dark">Update Promotion</h3>
	<hr />
	<form method="post" asp-action="Update" asp-controller="Promotion" enctype="multipart/form-data">
		<div class="row">
			<input asp-for="@Model.PromotionID" hidden />
			<div class="my-3">
				<label asp-for="@Model.Topic" class="form-label">Topic name</label>
				<input type="text" asp-for="@Model.Topic" class="form-control">
				<span asp-validation-for="@Model.Topic" class="text-danger"></span>

			</div>
			<div class="col-12 mt-5">
				<label asp-for="@Model.Content">Content</label>
				<textarea asp-for="@Model.Content" rows="3" class="form-control"> </textarea>
				<span asp-validation-for="@Model.Content" class="text-danger"></span>
			</div>
			<div class="col-12 mt-5">
				<label asp-for="@Model.StartDate">Start Date</label>
				<input asp-for="@Model.StartDate" rows="3" class="form-control"> </input>
				<span asp-validation-for="@Model.StartDate" class="text-danger"></span>
			</div>
			<div class="col-12 mt-5">
				<label asp-for="@Model.EndDate">End Date</label>
				<input asp-for="@Model.EndDate" rows="3" class="form-control"> </input>
				<span asp-validation-for="@Model.EndDate" class="text-danger"></span>
			</div>
			<div>
				<label asp-for="@Model.ImageUrl">ImageUrl</label>
				<input type="file" name="fileImage" asp-for="@Model.ImageUrl" rows="3" class="form-control" />
				<span asp-validation-for="@Model.ImageUrl" class="text-danger"></span>
			</div>


		</div>
		<button type="submit" class="btn btn-dark my-3">Update</button>
		<a asp-controller="Promotion" asp-action="Index" class="btn btn-secondary my-3" style="width:200px">
			Back to Promotion list
		</a>
	</form>
</div>


@*Validate on client side*@
@section Scripts {
	@{
		<script type="text/javascript">
			tinymce.init({
				selector: 'textarea',
				plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',
				toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',
			});
		</script>
		<partial name="_ValidationScriptsPartial" />
	}
}